//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicBookCollection.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static System.Net.WebRequestMethods;

    public partial class BookTable_1
    {
        public int Id { get; set; }

        //Validation

        //Title
        [Required(ErrorMessage = "Please enter a Title.")]  //i.e. required field
        [StringLength(60, MinimumLength = 1)]
        public string Title { get; set; }


        //Author
        [Required(ErrorMessage = "Please enter an Author.")]
        [StringLength(30, ErrorMessage = "Author name cannot exceed 30 characters")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s\-]*$", ErrorMessage = "The first letter of the author name must be a capitol letter.")]
        public string Author { get; set; }

        [Required(ErrorMessage = "Please select a Time Period.")]
        public string Time_Period { get; set; }

        //Genre
        [Required (ErrorMessage = "Please enter a Genre.")]
        [StringLength(30, ErrorMessage = "Genre cannot exceed 30 characters")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s\-]*$", ErrorMessage = "The first letter of the genre name must be a capitol letter.")]   //First letter of genre must be captial and the rest can be small, hyphens are allowed etc.
        public string Genre { get; set; }


        //Description
        [Required(ErrorMessage = "Please enter a Description.")]
        [StringLength(600, ErrorMessage = "Description cannot exceed 600 characters")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s\-]*$", ErrorMessage = "The first letter of the description must be a capitol letter.")]   //First letter of description must be captial and the rest can be small, hyphens are allowed etc.
        public string Description { get; set; }


        
        [RegularExpression(@"(https?:)?//?[^\'<>]+?\.(jpg|jpeg|gif|png)", ErrorMessage = "Invalid image URL.")]
        public string ImageURL { get; set; }
    }
}
